jaffle_shop:
  target: dev
  outputs:
    dev:
        type: databend
        host: tnf34b0rm--small-qerj.gw.aliyun-cn-beijing.default.databend.cn
        port: 443
        user: cloudapp
        pass: ckfgsdg8fxk1
        schema: debezium
        secure: True
